#!/bin/sh
set -e

if [ "$1" = "purge" ]; then
    rm -f /var/log/lsyncd/lsyncd.log
    rm -f /var/run/lsyncd.status
	rm -f /etc/lsyncd/lsyncd.conf.lua
	rm -f /etc/lsyncd/includes/extra
	rm -f /etc/lsyncd/includes/system
	rm -f /etc/lsyncd/includes/user
	rm -f /etc/logrotate.d/lsyncd-backup
	rm -f /etc/systemd/system/lsyncd.service.d/override.conf
	rm -f /usr/local/bin/lsync-merge-includes
	rmdir --ignore-fail-on-non-empty /etc/lsyncd || true
	rmdir --ignore-fail-on-non-empty /etc/systemd/system/lsyncd.service.d || true
    rmdir --ignore-fail-on-non-empty /var/log/lsyncd || true
fi

exit 0